### ISSUE TITLE
Micro stutters caused by stashes.

### ISSUE THREAD

**Issue by AffectedOne** [OGSR/OGSR-Engine#254]
Hello,

I was wondering, would it be possible to make stashes go online only when you search them? I think stashes work like that in Clear Sky, because i never noticed any stutters while playing it. No matter how much stuff i put in stash, it only lag the game when i open it. Maybe something like that can be ported or recreated on this version of engine? Thank you for your efforts, love your work on our beloved Shadow of Chernobyl.

**Comment by exostalker** [comment]
While fixing this from engine's perspective would be great, there's something like that done by ZRP recently:
ZRP-Specific Mini-Mods section here:
http://www.metacognix.com/files/stlkrsoc/index.html

It's an alternative all.spawn which edits each stash so that it stays online, slightly longer load times but the stashes don't need to load as you're moving in the level.

**Comment by AffectedOne** [comment]
Oh, thank you for pointing that to me. I'm little bit out of date when it comes to stalker mods, just recently started to catch up on whats new circling around. I'll definitely check it out. But, since ZRP is not so well known in russian speaking part of community, maybe author of this project will consider to implement something like that in engine.

Aciu dar karta, exo. :)

**Comment by joye-ramone** [comment]
Unfortunately there is not silver bullet how to fix this in engine for everybody.
But, there are plenty of options how to fix it via scripts, like custom switch distance for stashes, custom script stashes aka magic backpack https://github.com/dsh2dsh/op2ogse/blob/master/gamedata/scripts/dsh/dsh_rukzak.script etc
Engine should provide just possibility and that is what OGSR do right now
