### ISSUE TITLE
Controller broken?

### ISSUE THREAD

**Issue by exostalker** [OGSR/OGSR-Engine#458]
https://www.youtube.com/watch?v=gcOOhwsnNms

Hi, recorded this quite some time ago when last time replaying SOC with OGSR (no other mods alongside it at all) - I'm replaying it again now with the latest version, and still spotted this same behaviour from controller, really don't think this was the case in vanilla at all. Close by - tries to claw the actor ; far away - tries to do the usual psy attack ; but mid distance, he's just standing still there, useless, without trying anything at all - I believe the expected behaviour would be for him to chase the player so that at least he can claw the actor, right?

_p.s. I believe grass wave has been completely taken out? It's still in shader files, I enabled it but doesn't work anymore, kind of liked that effect adding some liveliness to the endless grass planes._

**Comment by joye-ramone** [comment]
> , really don't think this was the case in vanilla at all.
can you really confirm it with video or something? we never get any negative feedback about controller logic

**Comment by xrSimpodin** [comment]
the lack of a psi aura near controller is due to the fact that the version of aura that was in the ShOC engine was removed. To use the CoP-style psy aura, you need to add it to the config of controller:
```ini
;------------------------------------------------------------------------
; Influences
;------------------------------------------------------------------------
psy_linear_factor        =    1.0 ;1.5
psy_quadratic_factor    =    0
psy_max_distance        =    25 ;33.0
psy_max_power            =    6.4
psy_sound                =    monsters\controller\controller_presence_l
psy_pp_effector_name    =     postprocess_psi_aura ;psy_antenna
psy_pp_highest_at        =     0.05

[postprocess_psi_aura]
pp_eff_name        = radiation.ppe
pp_eff_cyclic    = 1
pp_eff_overlap  = true
radius_min        = 0.5
radius_max        = 1.1
```
This is described in the [**wiki**](https://github.com/OGSR/OGSR-Engine/wiki/%D0%90%D0%B4%D0%B0%D0%BF%D1%82%D0%B0%D1%86%D0%B8%D1%8F-%D0%BC%D0%BE%D0%B4%D0%BE%D0%B2-%D0%BF%D0%BE%D0%B4-%D1%8D%D1%82%D0%BE%D1%82-%D0%B4%D0%B2%D0%B8%D0%B6%D0%BE%D0%BA) for adapting mods to the engine.

> p.s. I believe grass wave has been completely taken out? It's still in shader files, I enabled it but doesn't work anymore, kind of liked that effect adding some liveliness to the endless grass planes.

We don't use grass wave now. It's possible that it doesn't work at all.
